### ISSUE TITLE
Sample learning data or Pre-trained model

### ISSUE THREAD

**Issue by HyungJoo-Kwon** [ziyangyeh/iMeshSegNet-Reg#1]
Hi, Thank you for Sharing this model.
Is there any sample learning data or pre-trained model for using iMeshSegNet-Reg?

**Comment by smoothumut** [comment]
Hi Ziyangyeh,
Really Thanks a lot for your great works and this conversion of the article. it is simple and honestly teaching me how to convert articles into implementations
I have started to try your implementation. But it would be awesome if you also share a sample learning data especially for  key_points data
Of course It would be gorgeus if you share a trained model : )
Thanks thanks in advance
Best regards

**Comment by ziyangyeh** [comment]
> Hi, Thank you for Sharing this model. Is there any sample learning data or pre-trained model for using iMeshSegNet-Reg?

Sorry, I don't have a pre-trained model. This is an experiment.

**Comment by ziyangyeh** [comment]
> Hi Ziyangyeh, Really Thanks a lot for your great works and this conversion of the article. it is simple and honestly teaching me how to convert articles into implementations I have started to try your implementation. But it would be awesome if you also share a sample learning data especially for key_points data Of course It would be gorgeus if you share a trained model : ) Thanks thanks in advance Best regards

Assume a single tooth(one batch) has Nx3 points with 5 key points, the corresponding heatmap should be, 5xNxN, and 5 is the channel.
